# github workflow cron job that runs npm start every hour
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'npm'
      - name: "npm install and start"
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          npm install
          npm start
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.3
        with:
          message: "Update from GitHub Actions"
      - name: Upload to Gist
        uses: stellarhub/push-gist-action@v1
        with:
          token: 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
          gist_id: 202ba403ba14b50f9a41dc5b9c8a746a
          file_path: stored.json

