# github workflow cron job that runs npm start every hour
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'npm'
      - name: "npm install and start"
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          npm install
          npm start
      - name: Add & Commit
        id: commit
        uses: EndBug/add-and-commit@v9.1.3
        with:
          message: "Update from GitHub Actions"
        

