name: Daily Stored JSON Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight

jobs:
  check-stored-json:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch and analyze stored.json
        env:
          GH_TOKEN: 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
        run: |
          gh api \
            -H "Accept: application/vnd.github.v3.raw" \
            /repos/JohnDeved/reddit-save-backup/contents/stored.json \
            > stored.json
          echo "Number of entries: $(jq length stored.json)"
          echo "CDN URLs:"
          jq -r '.[] | .cdnUrl | if type == "array" then .[] else . end' stored.json | while read -r url; do
            modified_url=$(echo "$url" | sed -E 's|https?://[^/]+|https://cdn.b-j.dev|')
            echo "- $modified_url"
          done
