name: Daily Stored JSON Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight

jobs:
  check-stored-json:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch and analyze stored.json
        env:
          GH_TOKEN: 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
        run: |
          warm_cache() {
            local url=$1
            local max_attempts=5
            local attempt=1
            
            while [ $attempt -le $max_attempts ]; do
              echo "Attempt $attempt for $url"
              cf_status=$(curl -sL "$url" -o /dev/null -w '%{http_code}' -H "Cache-Control: no-cache")
              
              if [ "$cf_status" = "200" ]; then
                echo "✅ Successfully warmed cache for $url"
                return 0
              else
                echo "⏳ HTTP status: $cf_status..."
              fi
              
              attempt=$((attempt + 1))
            done
            
            echo "❌ Failed to warm cache after $max_attempts attempts"
            return 1
          }

          gh api \
            -H "Accept: application/vnd.github.v3.raw" \
            /repos/JohnDeved/reddit-save-backup/contents/stored.json \
            > stored.json
          echo "Number of entries: $(jq length stored.json)"
          echo "Warming up CDN cache:"
          jq -r '.[] | .cdnUrl | if type == "array" then .[] else . end' stored.json | while read -r url; do
            modified_url=$(echo "$url" | sed -E 's|https?://[^/]+|https://cdn.b-j.dev|')
            echo "- $modified_url"
            warm_cache "$modified_url"
          done
