name: Daily Stored JSON Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight

jobs:
  check-stored-json:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch and analyze stored.json
        run: |
          gh api \
            -H "Accept: application/vnd.github.v3.raw" \
            /repos/JohnDeved/reddit-save-backup/contents/stored.json \
            > stored.json
          echo "Number of entries: $(jq length stored.json)"
